### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by galvesribeiro** [nachmore/unBand#31]
Hi!

How can I become a contributor member? Would like to code and help things here goes faster.

Thanks

**Comment by nachmore** [comment]
Sorry to hear that you feel that the project is going slow - though that's a great excuse to hop on board! :)

Contribution is fairly standard, clone the project and start sending through pull requests (we've already accepted 2). If you have ideas for large features it's worth discussing the design first in an issue here so that it doesn't conflict with other work / future expansion. 

Thanks!

**Comment by galvesribeiro** [comment]
Hello Oren, I just want to help.

If you have a list of planned features, maybe I can start by therer.

Thanks.
